spring.application.name=AiWeatherTool

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-nano
spring.ai.openai.chat.options.max-tokens=1000
weather.geocoding.base-url=https://nominatim.openstreetmap.org
weather.http.user-agent=AiWeatherTool/1.0 
server.port= 8081
